name: utils_validators
description: A Dart package that provides useful validators such as a name validator.
version: 1.2.0
homepage: https://github.com/EclesiasteVaz/utils_validators

environment:
  sdk: ">=3.2.4 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
